"""add birth_of_date to user

Revision ID: 218d010d1566
Revises: 3f1cb5596692
Create Date: 2025-06-21 21:07:29.449232

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "218d010d1566"
down_revision: Union[str, Sequence[str], None] = "3f1cb5596692"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("birth_of_date", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "birth_of_date")
    # ### end Alembic commands ###
